spring.application.name=redmine

# DataSource : Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@52.79.128.212:1521:xe
spring.datasource.username=redmine
spring.datasource.password=qhrwkqgksqlalfqjsgh

# Mybatis : Default Setting, Override
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.type-aliases-package=com.yedam.app
mybatis.mapper-locations=classpath:mapper/*/*.xml

# logging
logging.level.com.yedam.app=debug

# mail
spring.mail.host=smtp.daum.net
spring.mail.port=465
spring.mail.username=tjdcksgur.1@daum.net
spring.mail.password=tryetgzdfnyestgk

spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.daum.net
spring.mail.default-encoding=UTF-8

# upload path
app.upload.dir=uploads